server:
  port: 8088
  servlet:
    session:
      timeout: 6000


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #Monitor statistics interception filters
      filters: stat
      driver-class-name: org.mariadb.jdbc.Driver
      #Basic attributes
      url: jdbc:mariadb://localhost:3306/test
      username: olivier
      password: abc@1234
      #Configuration initial size/min/max
      initial-size: 1
      min-idle: 1
      max-active: 20
      #Get connection waiting timeout
      max-wait: 60000
      #How often is the interval to be tested to detect idle connections that need to be closed
      time-between-eviction-runs-millis: 60000
      #The minimum survival time of a connection in the pool
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #Open PSCache and specify the size of PSCache on each connection. Oracle is set to true, mysql is set to false. There are more sub-databases and sub-tables, it is recommended to set it to false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

  spring:
    data:
      elasticsearch:
        cluster-name: docker-cluster
        cluster-nodes: localhost:9300

  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 3000
    password:
      jedis:
        pool:
          ## The maximum number of connections in the connection pool (use a negative value to indicate no limit)
          #spring.redis.pool.max-active=8
          max-active: 8
          ## Connection pool maximum blocking waiting time (use a negative value to indicate no limit)
          #spring.redis.pool.max-wait=-1
          max-wait: -1
          ## The largest free connection in the connection pool
          #spring.redis.pool.max-idle=8
          max-idle: 8
          ## The smallest idle connection in the connection pool
          #spring.redis.pool.min-idle=0
          min-idle: 0
  session:
    store-type: redis
    timeout: 3000
  cache:
    type: redis


  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/vo/*.xml
  type-aliases-package: com.hak.mysite.model

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

swagger:
  show: true

logging:
  level:
    com.hak: DEBUG